### ISSUE TITLE
Could you please add a page for the 2024.8 release notes for languages other than English?

### ISSUE THREAD

**Issue by myamaguchi-jp** [AdobeDocs/experience-manager-cloud-service.ja-JP#1]
Issue in ./help/release-notes/release-notes-cloud/release-notes-current.md

While the release notes for 2024.8 are available in English as of 8/29 (US time), it appears that the other language versions are not yet available.
Could you please add a page for the 2024.8 release notes for languages other than English?

AEMaaCS Release Notes
Japanese: https://experienceleague.adobe.com/ja/docs/experience-manager-cloud-service/content/release-notes/release-notes/release-notes- current
English (released on 2024.08): https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/release-notes/release-notes-current

**Comment by mak-adobe** [comment]
@myamaguchi-jp ありがとうございます。G11N-17500のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@myamaguchi-jp 修正が完了しました。ご協力ありがとうございました。
