### ISSUE TITLE
Latest Release Note is not updated yet

### ISSUE THREAD

**Issue by horihara** [AdobeDocs/experience-manager-cloud-service.ja-JP#2]
Issue in ./help/release-notes/release-notes-cloud/release-notes-current.md

The original release note for build 2024.8 written in English has been already published on Aug 29th, however localized version such as Japanese, Deutsch, French etc. are still for the previous version 2024.7. Cloud you please update localized latest release note?

**Comment by mak-adobe** [comment]
@horihara  ありがとうございます。G11N-17500のチケットで対応を開始しました。

**Comment by horihara** [comment]
清水さん、

早速のご辍⒄\にありがとうございます！
恐れ入りますが、どうぞよろしくおいいたします。
折原

差出人: Mak Shimizu ***@***.***>
日付: 金曜日, 2024年9月13日 16:39
宛先: AdobeDocs/experience-manager-cloud-service.ja-JP ***@***.***>
CC: Hiroshi Orihara ***@***.***>, Mention ***@***.***>
件名: Re: [AdobeDocs/experience-manager-cloud-service.ja-JP] Latest Release Note is not updated yet (Issue #2)

EXTERNAL: Use caution when clicking on links or opening attachments.



@horihara<https://github.com/horihara> ありがとうございます。G11N-17500のチケットで辘蜷_始しました。

―

**Comment by mak-adobe** [comment]
@horihara git間の同期の問題でした。優先度上げて対応しております！

**Comment by mak-adobe** [comment]
@horihara 修正が完了しました。ご協力ありがとうございました。

**Comment by horihara** [comment]
@mak-adobe さま、
こちらの件、ご対応いただきましてありがとうございました！
