### ISSUE TITLE
Unnecessary codes are displayed

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/experience-manager-cloud-service.ja-JP#3]
https://experienceleague.adobe.com/ja/docs/experience-manager-cloud-service/content/overview/architecture

Unnecessary code such as heading-anchor is displayed throughout the Experience League Japanese site.

![image](https://github.com/user-attachments/assets/e0c07a62-6228-4437-b9b4-318eb21cd3f8)

**Comment by mak-adobe** [comment]
@mikobe2020  ありがとうございます。 G11N-17632 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@mikobe2020 修正が完了しました。ご協力ありがとうございました。
